Repository you-will-love-each-other/health-bot, pull requests merged in 2021-06, with the labels that each got.

#37 Add/beej status update
  .env.example
  bot.py
Labels: enhancement

#40 Add/ticket feature
  .env.example
  auxfunctions.py
  bot.py
Labels: enhancement

#41 Fix tickets
  bot.py
Labels: bug

#51 chore: set up sqlite
  .env.example
  .gitignore
  bot.py
  requirements.txt
  setup.py
Labels: enhancement

#48 Curation: fixes double curation / replaces a few variable calls / changes the footer
  bot.py
Labels: bug, enhancement

#49 Not allowing a user to create more than one ticket on the same ticket category
  bot.py
Labels: bug
